### ISSUE TITLE
outlook body parse

### ISSUE THREAD

**Issue by marcduren** [CaTzil/emailParser#1]
in parseBody($data) function
change    
    if (preg_match("/content\-type: ?text\/(html|plain); ?charset=(.*)/i", $data, $matches)) 
by
    if (preg_match("/content\-type: ?text\/(html|plain);\s*charset=(.*)/i", $data, $matches)) 

charset is on new line

**Comment by marcduren** [comment]
if (preg_match("/content-type: ?text/(html|plain);\s\*charset=(.*)/i", $data, $matches))

**Comment by CaTzil** [comment]
Thank you for submitting this issue 🙏🏼
