### ISSUE TITLE
Body parse empty

### ISSUE THREAD

**Issue by netred32** [CaTzil/emailParser#2]
parser->getPlainBody() and  $parser->getHTMLBody() result empty.....

Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit

Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 8bit

**Comment by CaTzil** [comment]
Can you elaborate regarding the issue?

Can you attach an example of a mail with the issue it will help me a lot.

**Comment by CaTzil** [comment]
@netred32 ping
